### ISSUE TITLE
Sponsoring Bereich!!!

### ISSUE THREAD

**Issue by JuliaPelzer** [stuvusIT/www_uno#13]
wir gewähren jedem Sponsor, dass sein Logo auf der Webseite auftaucht im Sponsoringbereich.. 
Dafür benötigen wir einen Sponsoringbereich. Wäre super, wenn der bald eingerichtet werden kann.

**Comment by Scriptkiddi** [comment]
brauche dazu die logos

**Comment by JuliaPelzer** [comment]
Okay, wenn der erst eingerichtet wird, wenn wir das erste Logo haben, passt es ja :+1 erstes Logo sollte am Montag kommen - schreibe dann nochmal
