### ISSUE TITLE
StartStartseite (UNO Logo)

### ISSUE THREAD

**Issue by JuliaPelzer** [stuvusIT/www_uno#15]
direkt auf den blauen Bereich bitte noch kompakt draufschreiben 
"
16. Oktober 2017
Einlass: 20.00 Uhr (Erstsemester)
21.30 Uhr (höhere Semester)
Eintrittspreis: 1 € (Erstsemester)
4 € (höhere Semester)
"

**Comment by Scriptkiddi** [comment]
passt das nicht weiter unten hin?

**Comment by JuliaPelzer** [comment]
gerne auch direkt drunter :) aber auf jeden fall dick und fett früh lesbar
