### ISSUE TITLE
Plakat

### ISSUE THREAD

**Issue by JuliaPelzer** [stuvusIT/www_uno#16]
sobald das Plakat steht - sollte man es irgendwo einfügen können, sowie die BIlder von den Treffen oder dem Abend vielleicht auch.
+ Verlinkung dort auf Facebook (oder woanders), da dort wieder weitere Bilder aus den letzten Jahren sind.

**Comment by Scriptkiddi** [comment]
äh was?

**Comment by JuliaPelzer** [comment]
Frage war, ob es irgendwo einen Bildbereich oder so gibt/geben wird (für das Plakat, Bilder.... vllt Link dort zur Facebookseite,...).

**Comment by Scriptkiddi** [comment]
war nicht geplant
