### ISSUE TITLE
Fakten - Textblock

### ISSUE THREAD

**Issue by JuliaPelzer** [stuvusIT/www_uno#42]
Fakten - Textblock sieht irgendwie etwas merkwürdig aus.
Vielleicht geht es als Blocksatz oder links bündig oder so. Sonst ist das mit dem Eintrittspreis beispielsweise merkwürdig: in der vierten Zeile steht Eintrittspreis: 1€...
in der zweiten Zeile, als wäre es unabhängig von der Zwischenüberschrift "Eintrittspreis", steht 4€... - kann man das irgendwie einrücken oder so? dass die Zusammengehörigkeit klar wird..
Danke ;-)

**Comment by dasJ** [comment]
Automatically bumping this issue because it was inactive for 43 days.
